#!/usr/bin/env bash
# A Bash script that displays all processes with USER, STARTED (hh:mm:ss), and COMMAND

echo "USER STARTED COMMAND"

ps -eo user,pid,lstart,cmd --no-headers | while read user pid dow mon day time year cmd; do
    # Format time to extract hh:mm:ss
    started_time=$(echo "$time" | cut -d':' -f1-3)
    echo "$user $started_time $cmd"
done
