#!/usr/bin/env bash
#this script create a loop that should be terminated if you find it's PID then kill it in other terminal than you are in.

# shellcheck disable=SC2009
PID=$(ps -ef | grep "[4]-to_infinity_and_beyond" | awk '{print $2}')

if [ -n "$PID" ]; then
    kill "$PID"
fi
