#!/usr/bin/env bash
# 7-highlander: Infinite loop, handles SIGTERM by printing a message and continuing.

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
