#!/usr/bin/env bash
# This script lists non-hidden files in the current directory, showing only the part after the first dash

for file in *; do

  [ -f "$file" ] || continue

  echo "${file#*-}"
done
